## Layer of Neurons
### We have seen how to create a single neuron from scratch in the previous chapter in this chapter we are going to see how we can create a layer of neurons.
Let us recall what a neuron does from previous chapter
1. Neouron takes $n$ number of inputs.
2. Mutiplies them with $n$ number of weights one weight for each input.
3. Adds a single bias at the end to produce a single valued output.
Key points to remember are:
- A neuron has as same number of weights as the number of inputs for instance a neuron has 10 inputs will also have 10 weights.
- No matter how many inputs are given to a neuron it only has a single bias value (sometimes we don't use bias value hence neuron can also have no bias value).
- No matter how many inputs are given to a neuron and if bias is given or not neuron produces a single valued output (scalar value).
### What is meant by a layer of neurons or simply a layer.
Putting it in simple terms if we bring one or more neurons together and arrange them to be in such a way that the input is acted upon be each single neuron independently and parallely is called layer or layer of neurons. Let us understand it more by an example say we have a single input $x_{0}$ and we have a single neuron say $n_{0}$ we give the neuron input $x_{0}$ and it produces a single output $y_{0}$. Now say that instead of a single neuron we have three neurons $n_{0}\space n_{1} \space n_{2}$ and we have the single input $x_{0}$ and we give it to each neuron seprately such that each neuron produces an output $y_{0}\space y_{1} \space y_{2}$ such that $n_{0}$ produces output $y_{0}$, $n_{1}$ produces output $y_{1}$ and $n_{2}$ produces output $y_{2}$. This arrangement in which we give input to each and every neuron independently to produce ouputs forms a layer.
#### The following example shows the layer of neurons is python:
- We have 4 inputs to our neuron $\textit{i.e}$ n = 4
- We have 3 neurons in a single layer and each neuron has a set of weigths of size 4 because input has size 4.
- We have 3 biases because we have 3 neurons and each neuron has only one bias so, 3 biases for 3 neurons.
- We then do some neuron maths to get output and we have three outputs because we have three neurons and one output per neuron gives us three outputs.

In [18]:
# For nice printing
from IPython.display import display, Latex

# inputs
inputs = [1, 2, 3, 2.5]

# weights for 1st neuron
weights1 = [0.2, 0.8, -0.5, 1]

# weights for 2nd neuron
weights2 = [0.5, -0.91, 0.26, -0.5]

# weights for 3rd neuron
weights3 = [-0.26, -0.27, 0.17, 0.87]

# bias for 1st, 2nd and 3rd neuron
bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
# Neuron 1:
inputs[0]*weights1[0] +
inputs[1]*weights1[1] +
inputs[2]*weights1[2] +
inputs[3]*weights1[3] + bias1,

# Neuron 2:
inputs[0]*weights2[0] +
inputs[1]*weights2[1] +
inputs[2]*weights2[2] +
inputs[3]*weights2[3] + bias2,

# Neuron 3:
inputs[0]*weights3[0] +
inputs[1]*weights3[1] +
inputs[2]*weights3[2] +
inputs[3]*weights3[3] + bias3]

print(f"Outputs from layer = {outputs}")

for i, op in enumerate(outputs, 1):
    out = f"Output for Neuron {i} is $y_{i}$ = {op}"
    display(Latex(out))




Outputs from layer = [4.8, 1.21, 2.385]


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

As we can see from above example a layer produces as many inputs as the number of neurons present in it for instance if a layer has 10 neurons the number of outputs from the layer will be 10.
#### We will now make the same layer of neurons using numpy and see how much our life becomes easier by writing small number of lines by using matrix multiplication.

In [22]:
import numpy as np
# inputs
inputs = np.array([1, 2, 3, 2.5])

# weights for 1st neuron
weights1 = np.array([0.2, 0.8, -0.5, 1])

# weights for 2nd neuron
weights2 = np.array([0.5, -0.91, 0.26, -0.5])

# weights for 3rd neuron
weights3 = np.array([-0.26, -0.27, 0.17, 0.87])

# bias for 1st, 2nd and 3rd neuron
bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
# Neuron 1:
np.dot(inputs, weights1) + bias1,

# Neuron 2:
np.dot(inputs, weights2) + bias2,

# Neuron 3:
np.dot(inputs, weights3) + bias3]

print(f"Outputs from layer = {outputs}")

for i, op in enumerate(outputs, 1):
    out = f"Output for Neuron {i} is $y_{i}$ = {op}"
    display(Latex(out))




Outputs from layer = [4.8, 1.21, 2.385]


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

We will now write bias in vector form and use that instead of bias1, bias2, bias3. Instead of writing bias at 3 places we write it in one line.

In [24]:
import numpy as np
# inputs
inputs = np.array([1, 2, 3, 2.5])

# weights for 1st neuron
weights1 = np.array([0.2, 0.8, -0.5, 1])

# weights for 2nd neuron
weights2 = np.array([0.5, -0.91, 0.26, -0.5])

# weights for 3rd neuron
weights3 = np.array([-0.26, -0.27, 0.17, 0.87])

# bias for 1st, 2nd and 3rd neuron
biases = np.array([2, 3, 0.5])

outputs_ = [
# Neuron 1 dot product:
np.dot(inputs, weights1),

# Neuron 2 dot product:
np.dot(inputs, weights2),

# Neuron 3 dot product:
np.dot(inputs, weights3)]

outputs = outputs_ + biases

print(f"Outputs from layer = {outputs}")

for i, op in enumerate(outputs, 1):
    out = f"Output for Neuron {i} is $y_{i}$ = {op}"
    display(Latex(out))

Outputs from layer = [4.8   1.21  2.385]


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

From this section onwards we assume that reader has knowledge of $\textbf{Matrix Multiplication and Transpose of a Matrix}$. However shot explaination of Tranpose and demonstration is given below.
- Transpose of a matrix is given by interchanging rows with columns.

In [25]:
matrix_ = np.array([[1,2,3],
                    [4,5,6],])

# Tranpose of the matrix will be
matrix_.T

array([[1, 4],
       [2, 5],
       [3, 6]])

We do not want to write weights for each neuron in seperate variables

In [28]:
import numpy as np
# inputs
inputs = np.array([1, 2, 3, 2.5])

# weights for 1st, 2nd, 3rd neuron
weights = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5],
                    [-0.26, -0.27, 0.17, 0.87]])

# bias for 1st, 2nd and 3rd neuron
biases = np.array([2, 3, 0.5])

outputs = np.dot(inputs, weights.T) + biases

print(f"Outputs from layer = {outputs}")

for i, op in enumerate(outputs, 1):
    out = f"Output for Neuron {i} is $y_{i}$ = {op:.2f}"
    display(Latex(out))

Outputs from layer = [4.8   1.21  2.385]


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Until this point we have only seen one input vector to the neuron but there can be many input vectors which are given to neuron called batch of inputs. we will see what a batch of inputs is from given example all fundamentals remain unchanged.

In [38]:
import numpy as np
# inputs
inputs = np.array([[1, 2, 3, 2.5],
                    [2.0, 5.0, -1.0, 2.0],
                    [-1.5, 2.7, 3.3, -0.8]])

# weights for 1st, 2nd, 3rd neuron
weights = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5],
                    [-0.26, -0.27, 0.17, 0.87]])

# bias for 1st, 2nd and 3rd neuron
biases = np.array([2, 3, 0.5])

outputs = np.dot(inputs, weights.T) + biases

print(f"Outputs from layer for 3 inputs each containing 3 elements are:\n{outputs}")


Outputs from layer for 3 inputs each containing 3 elements are:
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


After basic understanding of these concepts we are ready to give our code some touch of Pytorch. We will mimic the Linear class present in Pytorch which is used to create a layer of neurons.

In [60]:
class Linear:
    def __init__(self):
        self.weigths = np.array([[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5],
                    [-0.26, -0.27, 0.17, 0.87]])
        self.biases = np.array([2, 3, 0.5])

    def __call__(self, inputs):
        return self.forward(inputs)

    def forward(self, inputs):
        outputs = np.dot(inputs, weigths.T) + self.biases
        return outputs

# inputs
inputs = np.array([[1, 2, 3, 2.5],
                    [2.0, 5.0, -1.0, 2.0],
                    [-1.5, 2.7, 3.3, -0.8]])

# A single layer if 3 neurons initialise                  
single_layer_of_3_neurons = Linear()

# feed forward the inputs to the neurons
ouputs = single_layer_of_3_neurons.forward(inputs)

#  or we can also write instead of above feed forward
outputs = single_layer_of_3_neurons(inputs)

# print the outputs
print(f"Ouput of the layer :\n{outputs}")

Ouput of the layer :
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


Usually we dont set weigths and biases manually we either randomly give some initial values to weights and biases or use other sophesticated methods to initialise them for now we will use random values to initialise the weights and biases. However the results you will see below do not match with the results we got above because we are initializing the weights and biases with random values and each time you run it will cahange the results. (Note:- If you want to get same results then as this notebook we use seed method for reproducability.)
- n_inputs means number of inputs (remember the difference between number of inputs and batch of inputs). We use this to initialise the weights beacuse number of weights = number of inputs.
- n_neurons means number of neurons that one layer is going to have.

In [66]:
# for getting same results as this use seed
np.random.seed(42)

# define a linear class that will create a layer of neurons
class Linear:
    def __init__(self, n_inputs, n_neurons):
        self.weigths = np.random.randn(n_neurons, n_inputs)
        self.biases = np.zeros(n_neurons)

    def __call__(self, inputs):
        return self.forward(inputs)

    def forward(self, inputs):
        outputs = np.dot(np.array(inputs), weigths.T) + self.biases
        return outputs

    def __repr__(self):
        n_n, n_i = self.weigths.shape 
        return f"This is a Layer of neurons having {n_n} neurons and {n_i} inputs."

# inputs
inputs = np.array([[1, 2, 3, 2.5],
                    [2.0, 5.0, -1.0, 2.0],
                    [-1.5, 2.7, 3.3, -0.8]])

# A single layer if 3 neurons initialise                  
single_layer_of_3_neurons = Linear(4, 3)

# feed forward the inputs to the neurons
ouputs = single_layer_of_3_neurons.forward(inputs)

#  or we can also write instead of above feed forward
outputs = single_layer_of_3_neurons(inputs)

# print the outputs
print(f"Ouput of the layer :\n{outputs}")

Ouput of the layer :
[[ 2.8   -1.79   1.885]
 [ 6.9   -4.81  -0.3  ]
 [-0.59  -1.949 -0.474]]


Example code of Layer in Pytorch:
In pytorch the code for creating the Layer having 3 neurons and batch of input where each input has 4 elements is given as follows. 
We are doing same thing we have done above using Pytorch Library.

In [105]:
import torch
import torch.nn as nn

torch.manual_seed(42)

# inputs
inputs = np.array([[1, 2, 3, 2.5],
                    [2.0, 5.0, -1.0, 2.0],
                    [-1.5, 2.7, 3.3, -0.8]], dtype=np.float32)

# Create a layer using pytroch
layer = nn.Linear(in_features=4, out_features=3)

# print the results
print(f"Output of the layer using Pytorch:\n{layer(torch.tensor(inputs)).detach().numpy()}")

Output of the layer using Pytorch:
[[ 2.3785372   0.16377497  1.4859807 ]
 [ 4.2447104   1.1837987  -0.95887226]
 [ 0.16251713 -0.53376347 -0.05115128]]


### Conclusion and Future Work:
- We have implemented and understood what is layer or layer of neurons.
- We have pytorchified our code so that it will mimic pytorch classes and functions that we are going to see in future.
- We have seen inputs and batch of inputs.
- We have seen matrix multiplication and trasnpose of matrix in action.
- We have addressed the previous future work in this by making our code more modular and implementing a layer of neurons instead of single neuron.
- In future we would like to see FCCNN $\textit{i.e}$ many layers stacked on top of each other called a neural network.